### ISSUE TITLE
Labeled Value Displays using /pin./ not showing data

### ISSUE THREAD

**Issue by Gun-neR** [avin/blynk-web-client#1]
It seems if the /pin./ setting is used, then additional "labeled" values are shown, but not the vPin data.

It seems to treat the /pin./ as data not as a placeholder for the data

![image](https://user-images.githubusercontent.com/28169425/52194989-e8153a00-280a-11e9-86bc-6d6fcff4da00.png) 
![image](https://user-images.githubusercontent.com/28169425/52195099-4b06d100-280b-11e9-84fd-d7bda2da9d3f.png)

**Comment by avin** [comment]
Fixed 
@Gun-neR can you check it for your project?

**Comment by Gun-neR** [comment]
Yes, they are displaying properly now. Thanks.
