### ISSUE TITLE
Blynk Report widget

### ISSUE THREAD

**Issue by paulhanga** [avin/blynk-web-client#10]
Hi Avin,

first  I really enjoyed your work. 
 I've put it on my raspberry pi and it worked great. 
Could you please add the report widget on your next release?
Here are some screenshots:
![data](https://user-images.githubusercontent.com/25500767/68664775-2fbab600-0541-11ea-9650-67e68657a1ca.JPG)
![chart1](https://user-images.githubusercontent.com/25500767/68664777-2fbab600-0541-11ea-8159-98a233e45939.JPG)

Thanks a lot for your work
Paul

**Comment by avin** [comment]
Hey, Paulhanga!
Can you attach screenshot of original blynk app  from your phone with this "report-widget"?

**Comment by paulhanga** [comment]
Here u are. 
![blynk app](https://user-images.githubusercontent.com/25500767/68681734-360e5980-0564-11ea-8c12-4e223c29ae5e.JPG)

**Comment by avin** [comment]
Sorry, no plan to contribute this feature
