### ISSUE TITLE
Buttons not changing STATES correctly

### ISSUE THREAD

**Issue by Gun-neR** [avin/blynk-web-client#2]
Buttons set as momentary and 0-1 work as should.

But if set as 'switch' they seem to switch state only the first press, thus if turning ON, they stay ON, until turned OFF in Blynk App,

I have also noticed that if in Blynk App, a Button is set to a reverse Min-MAX state (e.g. 1-0) this is not replicated in this web client.

**Comment by avin** [comment]
just fixed this problem, can you check it again?

**Comment by Gun-neR** [comment]
Yes, the switch works now.  Thanks.

The inverse MIN MAX also work now...  However, as a side note, you cannot see any labeling with switch ON when colour is white :)

![image](https://user-images.githubusercontent.com/28169425/52329317-470fb600-29a7-11e9-94af-f7d030d0c86b.png)

**Comment by avin** [comment]
Ahh, missed this moment. Fixed now
![image](https://user-images.githubusercontent.com/36100/52330841-853cc200-2a07-11e9-8ee3-d227b922a7fe.png)

**Comment by Gun-neR** [comment]
Perfect :)
