### ISSUE TITLE
Web Client controls not registering on device

### ISSUE THREAD

**Issue by Gun-neR** [avin/blynk-web-client#3]
Any widget state change from this Web client, will register on the Blynk App... However, it will NOT actually register on the device as a state change.  

Acts exactly like doing a `virtualWrite()` without a `syncVirtualPin()` command in a sketch.  

Tested using Local Server only.

**Comment by avin** [comment]
@Gun-neR I enabled bridge mode for write pin operations. It should works fine now. Can you test it with your hardware projects?

**Comment by Gun-neR** [comment]
OK, now any button presses, slider movements, etc, will result in proper device code responses.  Thank you.
