### ISSUE TITLE
No working to my hosting

### ISSUE THREAD

**Issue by langtupt** [avin/blynk-web-client#6]
Dear Mr. Avin,
Kindly please help check, i have upload code to my hosting and do not connect server.
Can you help check?
![image](https://user-images.githubusercontent.com/18097488/52515823-3edba300-2c53-11e9-9a8e-69784f978eff.png)

**Comment by avin** [comment]
Hey, @langtupt! Seems like you are using HTTPS on your site. Try to use simple HTTP, I think it's the problem.

**Comment by langtupt** [comment]
Dear Mr. Avin
I'm try no https and it's working now.
Thank you very much for blynk web
![image](https://user-images.githubusercontent.com/18097488/52542736-7d996680-2dd5-11e9-879e-63501ab33f61.png)
