### ISSUE TITLE
Blynk device selector widget not supported yet?

### ISSUE THREAD

**Issue by noobGB** [avin/blynk-web-client#8]
Hi Avin,

Thank you for this web client, I really appreciate your hard work. I am working on a project which uses Blynk device selector widget but when I use this web dashboard all the button widgets stops working, could you please let me know if it is expected behavior and how soon should we expect [device selector] widget to be supported on web dashboard??
![Avin_blynk_web_client2](https://user-images.githubusercontent.com/19291539/54084646-50e75900-4359-11e9-9a1d-faabca257bee.JPG)

**Comment by philo-create** [comment]
Hey Avin.Is this function still not available

**Comment by avin** [comment]
Sorry but public Blynk API is very shorten to have an ability to release these features.
